services:
  kliq-collect:
    hostname: ${KLIQ_COLLECT__HOST}
    build:
      context: ../modules/kliq-collect
      dockerfile: Dockerfile
    ports:
      - ${KLIQ_COLLECT__PORT}:${KLIQ_COLLECT__PORT}
    depends_on:
      kliq-kafka:
        condition: service_healthy
      kliq-kafka-setup:
        condition: service_completed_successfully
    environment:
      KLIQ_COLLECT__ENV: ${KLIQ_COLLECT__ENV}
      KLIQ_COLLECT__VERBOSE: ${KLIQ_COLLECT__VERBOSE}
      KLIQ_COLLECT__HOST: ${KLIQ_COLLECT__HOST}
      KLIQ_COLLECT__PORT: ${KLIQ_COLLECT__PORT}
      KLIQ_COLLECT__ADDR: ${KLIQ_COLLECT__ADDR}
      KLIQ_COLLECT__KAFKA_ADDR: ${KLIQ_COLLECT__KAFKA_ADDR}
      KLIQ_COLLECT__KAFKA_TOPIC: ${KLIQ_COLLECT__KAFKA_TOPIC}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${KLIQ_COLLECT__ADDR}/healthcheck"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s