%% docs/resources/kliq-diagram.png

graph LR
%% Components
    client((
        <div style="width:48px;height:auto;">
            <img src="https://raw.githubusercontent.com/gist/csgn/bf32c290e6a395de55268f75f0e5af2f/raw/f4477914c6a4027c1ee4a047cf80a56829931b1b/user.svg"/>
        </div>
    ))

    kliq_collect(
        <div style="width:48px;height:auto;margin:0 3px;">
            <img src="https://raw.githubusercontent.com/gist/csgn/bf32c290e6a395de55268f75f0e5af2f/raw/7e32bac6bfbbc40b314eff31adab396f3854b1c1/golang.svg"/>
        </div>
        Collector
    )

    kliq_kafka(
        <div style="width:48px;height:auto;margin:5px 48px;">
            <img src="https://raw.githubusercontent.com/gist/csgn/bf32c290e6a395de55268f75f0e5af2f/raw/7e32bac6bfbbc40b314eff31adab396f3854b1c1/apache-kafka.svg"/>
        </div>
        Event Broker
    )

    kliq_stream(
        <div style="width:48px;height:auto;margin:5px 48px;">
            <img src="https://raw.githubusercontent.com/gist/csgn/bf32c290e6a395de55268f75f0e5af2f/raw/7e32bac6bfbbc40b314eff31adab396f3854b1c1/apache-spark.svg"/>
        </div>
        Stream Job
    )

    %% Styles
        style client                    stroke:#ffffff,fill:#ffffff
        style kliq_collect              stroke:#111111
        style kliq_kafka                stroke:#000000,fill:#eeeeee
        style kliq_stream               stroke:#ca4000
    %% %
%% %

%% Subgraphs
    subgraph Collect Service
        kliq_collect
        kliq_kafka
        kliq_stream
    end

    %% Styles
    %% %
%% %

%% Relations
    client       --raw event--> kliq_collect
    kliq_collect --raw event--> kliq_kafka --raw event--> kliq_stream
%% %